### ISSUE TITLE
Can't add feeds

### ISSUE THREAD

**Issue by mburtis** [mattkatz/Orbital-Feed-Reader#6]
I tried installing and setting up this plugin today. I wasn't able to successfully add any feeds. When I click on the "+" a popup window appears asking to enter a URL or upload a file. I entered a URL (both site address and feed address) and clicked the "Check a URL." A spinner indicated something was happening, but nothing ever did. There was no confirmation that a feed was found or a way to then confirm I wanted to use the URL. 

I then tried an OPML file, and upon uploading nothing seemed to happen. I tried several times, and suddenly all the feeds in the file appeared in the feed listing (several times since I had tried to upload the file several times). However, I couldn't update the feeds and actually see any items. I tried click on individual feeds (again a spinner appeared, but nothing happened). I also tried clicking the arrow icon in the menu above the feeds, but nothing happened.

**Comment by mattkatz** [comment]
closing because no feedback and hopefully recent changes have made this more robust.
