### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by abemrose** [mattkatz/Orbital-Feed-Reader#7]
Hello. I tried to install the reader in my blog. When I activated it, it returned a massive fatal error and locked me out of the admin panel while also making it impossible for anyone to read the blog itself. I had to get my web host to rename the Orbital file so that I could have access to the admin panel again. 

I'm not going to risk trying to run this program again. It's obviously not working properly. I've noticed that many of the Word Press plugins are buggy, at best.

**Comment by mattkatz** [comment]
I'm closing this because I haven't gotten to it yet and I'm not actively working on it. Any logs are probably gone.  

If Ann does want to re-open, no problem, i'd love to take a look now that I've got slightly more free time.
