### ISSUE TITLE
Feeds are not displayed :(

### ISSUE THREAD

**Issue by stephanwaba** [mattkatz/Orbital-Feed-Reader#9]
Just installed feed reader on current WP version  4.3.1–de_DE.
Unfortunately, no feeds are displayed. It just says "That's all we've got so far!", but there are numbers in the list of feeds on the left hand side; so there are obviously unread posts.
Do you know anything about this?
Thanks!

**Comment by mattkatz** [comment]
Hi @stephanwaba  - sorry for taking so long to get back to you. Had a kid and my open source stuff was on the back burner for a bit. 

Can you let me know what user role or type you are in wordpress?  Are you an admin or an editor?

Did you ever have anything show or is this always the experience.

Do you want to attach the contents of the javascript console log and/or your wordpress logs?  If you don't know how to do either of those, let me know.

**Comment by mattkatz** [comment]
Ugh - it's been so long - BUT! I think the latest version, 0.2.2 fixed this. 
Short version - there was a database collation that I wasn't using/testing with that did not work with my installation. I think you were using this method and I've tracked down the issue. 

Please uninstall the plugin and then re-install it. It should work magically for you!

If you want to be extra helpful, you could add these two lines to your wp-config.php file *before* re-installing the plugin:

    // Enable WP_DEBUG mode
    define('WP_DEBUG', true);
    // Enable Debug logging to the /wp-content/debug.log file
    define('WP_DEBUG_LOG', true);
    // Disable display of errors and warnings 
    define('WP_DEBUG_DISPLAY', false);

Those will produce a file called debug.log in the  wp-content folder.
If it *doesn't* work, you could attach this file and it would greatly help me figure out what's happening.
If it does work, just delete those lines from the config file and you're all set!
